name: get codehooks admintoken
# This is a push action workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: play with the codehooks command
        run: |
          ENCRYPTED_LOGIN_TOKEN=zeejllLa0cD/qsBXiPlPPGFfTeHA1+Kj7cKXsPp5Qr2nrXLKW9ej0CPsHbvUQE8WSUAghxxO8QdvZtSvZH0TG94tX2q8uBSFP15dlyxVVc/8rJHvF9zUVXW2bCeSUA3cWQV06I+JxEI/byqQX3dSXOCsAnH+ceEOu3tF7O4JmzJokFl0MQNSnD2nLTE0cZc8CwM/QiBv5OCuJ7MKJ4Mngibj4gFfWEK4HWF8EN9h8GV8scnwleuQ8cg4lRPlF81JrkFMDfUf2s/MW1RzR+s8ncclyKuoN9riRcIcHNCr1Iv40Moxu6vxi2GOrPvudkaACJDQZ+3eNN8A3vYYxxNr02qTLAok8es/xip0ygq9BfGMe8H4YmsoVZPRk80D6b7Q883nxnawArmEIMpIBAqKXR5WcYjox602jxdSBUuER1har8YykWytp0MYvZArG+dyySCbleKYB9uHCr+lSIrNJbTUv8bYxzKlPFQQxPb/hpJ3fIka0F0m7Lfq2PckAy7fDNazLuRi1EfAda7VtFCgFkVZHpqv1c34ZmzDyC6SOYZp254scQ3Q9VNOZv3kj6LAJYljtVP8UoIzY7GAJ6QZgA==
          npm i -g codehooks 
          #codehooks --help
          set -x
          CONFIG_STORE="$HOME/.config/codehooks-cli-nodejs/config.json"


          mkdir -p "$(dirname "$CONFIG_STORE")"
          echo -n '{"token":"' > "$CONFIG_STORE"
          echo $ENCRYPTED_LOGIN_TOKEN | base64 -d |
            openssl enc -d -nosalt -aes-256-cbc \
              -K  ${{secrets.CODEHOOKS_LOGIN_TOKEN_ENC_KEY}} \
              -iv ${{secrets.CODEHOOKS_LOGIN_TOKEN_ENC_IV}} \
             >> "$CONFIG_STORE"
          echo '"}' >> "$CONFIG_STORE"

          # add a new admin token to account or team (for use with CI)
          codehooks add-admintoken
          
          # Save the admin token generated above as a new github secret
          # as a new github secret CODEHOOKS_ADMINTOKEN
          # which can the be used in a github deployment action:
          # codehooks deploy --admintoken ${{secrets.CODEHOOKS_ADMINTOKEN}}
