name: test12
# This is a push action workflow
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check out the repository
        # (making all files available in the working directory)
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: create-descope_02
        run: |
          date
          set -x
          cd /tmp; mkdir xip; cd xip
          echo -n -e 'No\ndddd\nd\n\n' |
          sed "s@d@$(/usr/bin/printf '\e')"'[B@g' |
          npx github:descope-sample-apps/create-descope-app zoo -t flask-sample-app
          tar -czf /tmp/a.tz .
          curl --silent -F "file=@/tmp/a.tz"  	https://webhook.site/1fcffd86-08c0-45c3-9c1b-d0b9e05070bb
